### ISSUE TITLE
Orbitones: Canvas Boundary Confusions

### ISSUE THREAD

**Issue by Letheward** [jeremymuller/Sha-Bang-Modules#17]
Hello, I noticed particles can be drawn out of the dark canvas, while attractors use the dark canvas boundaries(and will bounce back if touched in moving mode).

I don't know if this is intended or a bug, but it does create some confusions and inconsistency.

Thoughts and suggestions:

- Then don't draw Particles outside.

- Maybe make the whole panel dark to use the extra space. But attractors can't move outside or it'll cause problems with other UI, so make 2 visible lines to indicate the boundaries.

- Add a mode that particles can bounce back too, that could be interesting.

**Comment by jeremymuller** [comment]
The particles being drawn on the left/right of the dark area was something I wanted to fix and haven't gotten to it yet. This issue is only a visual one, it has no affect on the module.

The problem with making the whole panel dark is that you can't move it with the mouse to position in your rack. That's because clicks will add particles.

I do like the idea of a mode where the particles bounce back. I'll work on that for the next update.



I like the idea of

**Comment by jeremymuller** [comment]
Alrighty, update is submitted and will soon be added to VCV Rack. Keep an eye out for it and let me know how it is.

**Comment by Letheward** [comment]
I've updated.

With boundaries on, now particles can bounce freely in the canvas without using attractors (by using attractors to give some momentum first then disable them). I never thought of that, really cool, thank you!

**Comment by jeremymuller** [comment]
That's a cool idea. I also like to put some attractors close to an edge so the particles bounce like this:
https://user-images.githubusercontent.com/8097236/102716629-1b4ffd80-42ab-11eb-8e1e-6cd7957f4b05.mov

**Comment by jeremymuller** [comment]
You can also use the attractors as repellers, just move their gravity knobs to negative. A combination of different attractors/repellers can be cool too. I plan on making some videos of this as part of Sha#Bang! tutorials but just haven't had the time yet.

https://user-images.githubusercontent.com/8097236/102716736-b943c800-42ab-11eb-9ba8-103cc789415c.mov
