### ISSUE TITLE
Cosmosis and Neutrinode request

### ISSUE THREAD

**Issue by coolname123** [jeremymuller/Sha-Bang-Modules#5]
Hey, I just downloaded your modules and am having a ton of fun with them, but was just curious why you didn't add any clock inputs for bpm or speed on your cosmosis and neutrinode modules... without those sorts of inputs I'm finding it really challenging to incorporate them into larger compositions (a reset input would also be nice for that matter). Especially since one of the modules in your pack is a complex clock of sorts, just seems odd to not have a way for those modules to interact.

**Comment by jeremymuller** [comment]
@coolname123 thanks for your interest in my modules and I'm glad you're enjoying them. 

As for the clock inputs, it's on my TODO list. Since they are atypical "sequencers" and don't have noticeably discrete time steps, I originally was thinking of them as generators of some sort. But as you mentioned, it does make it difficult to integrate with other modules. However, a reset input would only work for Cosmosis. In Neutrinode each node has a random start point – this is done purposefully so they don't all trigger pulses at the same time – so a reset option would ruin the overlaps of each node.

**Comment by isabelgk** [comment]
Hi @jeremymuller ! I just wanted to let you know that Omri Cohen was interested in this feature, so I'm sure if it can be done, it'll probably get a good amount of traction and use in the community. These modules are really awesome... Thanks for your work!

**Comment by jeremymuller** [comment]
Thanks @isabelgk, I'm glad you like them. I'm working on adding more inputs to both Cosmosis and Neutrinode. However, adding a clock input on these modules doesn't really make sense (or work really well) since they're continuous and not discrete time increments. I tried this and it just makes it become a very jerky and skip around, when this same result can be achieved by adding an input to BPM. Therefore, I will probably add inputs to control on/off, BPM, reset and/or randomize start depending on the module.

**Comment by isabelgk** [comment]
That's fantastic and I think will do the trick! Thanks again :)

**Comment by jeremymuller** [comment]
Will be in the next update whenever VCV Rack manager do the next update build, probably in a few days.
