### ISSUE TITLE
Question on PolyRhytm accuracy

### ISSUE THREAD

**Issue by S0210** [jeremymuller/Sha-Bang-Modules#51]
Dear Jeremy,

I know that my measurement of BPM isn't too scientific and I also acknowledge that these differences impact musicality only in extreme cases. But could you please confirm if PolyRhytm is meant to behave like this?

My expectations for the outputs was 20 BPM, 40 BPM, 120 BPM, and 360 BPM.

<img width="394" alt="image" src="https://user-images.githubusercontent.com/34127628/147404030-8ee9f197-5dda-4024-885e-84fc9b04a8fc.png">

Best regards, Andras

**Comment by jeremymuller** [comment]
I'll look at the implementation. I'm pretty sure I do the same mechanics as VCV Seq3 with the additional layers of rhythms. But did you try hitting reset on the clock?

**Comment by Petervos2018** [comment]
@S0210 
Did you right-click the polyrhythm clock BPM knob and enter 20, or did you rotate the knob until it said 20. 
Because there will be a difference.
Here I entered 20 and all is well :

![afbeelding](https://user-images.githubusercontent.com/46076474/147415933-09931298-1dfc-4577-943f-4591729f1bb7.png)

**Comment by S0210** [comment]
As I wasn't sure so I gave another few tries. The module is as precise as a dream indeed. My apologies, most likely I turned the tempo knob by mistake. 

Thanks for pointing out the difference @Petervos2018  ! I'm closing the case.

**Comment by jeremymuller** [comment]
thanks, @Petervos2018
